name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Format with Prettier
        run: yarn prettier --check src
      - name: Lint with ESLint
        run: yarn eslint src
      - name: Check type compilation with TypeScript
        run: yarn type-check
      - name: Run tests with Jest
        run: yarn test
